import type { Asset } from '@/lib/types';

export const ASSETS: Asset[] = [
  { id: 'A-PERNIS', name: 'Pernis Refinery', segment: 'downstream', region: 'EMEA', country: 'Netherlands', coords: [4.40, 51.88], headcountBand: '2000+', climateZone: 'temperate' },
  { id: 'A-PEARL-GTL', name: 'Pearl GTL', segment: 'integrated-gas', region: 'EMEA', country: 'Qatar', coords: [51.55, 25.90], headcountBand: '2000+', climateZone: 'arid' },
  { id: 'A-PRELUDE', name: 'Prelude FLNG', segment: 'integrated-gas', region: 'APAC', country: 'Australia (offshore)', coords: [123.42, -13.78], headcountBand: '100-500', climateZone: 'offshore' },
  { id: 'A-QGC', name: 'QGC LNG', segment: 'integrated-gas', region: 'APAC', country: 'Australia', coords: [150.51, -27.16], headcountBand: '500-2000', climateZone: 'arid' },
  { id: 'A-BONGA', name: 'Bonga FPSO', segment: 'upstream', region: 'EMEA', country: 'Nigeria (offshore)', coords: [4.50, 4.45], headcountBand: '100-500', climateZone: 'offshore' },
  { id: 'A-NDA', name: 'Niger Delta Assets', segment: 'upstream', region: 'EMEA', country: 'Nigeria', coords: [6.30, 5.10], headcountBand: '500-2000', climateZone: 'tropical' },
  { id: 'A-PERMIAN', name: 'Permian Basin Operations', segment: 'upstream', region: 'AMER', country: 'United States', coords: [-102.55, 31.85], headcountBand: '500-2000', climateZone: 'arid' },
  { id: 'A-DEERPARK', name: 'Deer Park Manufacturing', segment: 'downstream', region: 'AMER', country: 'United States', coords: [-95.13, 29.70], headcountBand: '2000+', climateZone: 'tropical' },
  { id: 'A-NORCO', name: 'Norco Manufacturing', segment: 'downstream', region: 'AMER', country: 'United States', coords: [-90.41, 29.99], headcountBand: '2000+', climateZone: 'tropical' },
  { id: 'A-SCOTFORD', name: 'Scotford Complex', segment: 'downstream', region: 'AMER', country: 'Canada', coords: [-113.10, 53.71], headcountBand: '500-2000', climateZone: 'continental' },
  { id: 'A-MOERDIJK', name: 'Moerdijk Chemicals', segment: 'downstream', region: 'EMEA', country: 'Netherlands', coords: [4.62, 51.66], headcountBand: '500-2000', climateZone: 'temperate' },
  { id: 'A-RHEINLAND', name: 'Rheinland Refinery', segment: 'downstream', region: 'EMEA', country: 'Germany', coords: [6.85, 50.95], headcountBand: '2000+', climateZone: 'temperate' },
  { id: 'A-BUKOM', name: 'Bukom Manufacturing Site', segment: 'downstream', region: 'APAC', country: 'Singapore', coords: [103.78, 1.23], headcountBand: '2000+', climateZone: 'tropical' },
  { id: 'A-NANHAI', name: 'CNOOC-Shell Nanhai Petrochemicals', segment: 'downstream', region: 'APAC', country: 'China', coords: [113.10, 22.55], headcountBand: '2000+', climateZone: 'tropical' },
  { id: 'A-GOM-AUGER', name: 'Auger TLP', segment: 'upstream', region: 'AMER', country: 'United States (offshore)', coords: [-92.43, 27.55], headcountBand: '<100', climateZone: 'offshore' },
  { id: 'A-GOM-PERDIDO', name: 'Perdido Spar', segment: 'upstream', region: 'AMER', country: 'United States (offshore)', coords: [-94.90, 26.13], headcountBand: '<100', climateZone: 'offshore' },
  { id: 'A-NS-NELSON', name: 'Nelson Platform', segment: 'upstream', region: 'EMEA', country: 'United Kingdom (offshore)', coords: [1.92, 56.91], headcountBand: '100-500', climateZone: 'offshore' },
  { id: 'A-NS-SHEARWATER', name: 'Shearwater Platform', segment: 'upstream', region: 'EMEA', country: 'United Kingdom (offshore)', coords: [1.85, 57.50], headcountBand: '100-500', climateZone: 'offshore' },
  { id: 'A-VITO', name: 'Vito FPS', segment: 'upstream', region: 'AMER', country: 'United States (offshore)', coords: [-89.10, 28.80], headcountBand: '<100', climateZone: 'offshore' },
  { id: 'A-ETC-AMS', name: 'Energy Transition Campus Amsterdam', segment: 'renewables', region: 'EMEA', country: 'Netherlands', coords: [4.93, 52.39], headcountBand: '500-2000', climateZone: 'temperate' },
  { id: 'A-RBR', name: 'Rotterdam Biofuels Refinery', segment: 'renewables', region: 'EMEA', country: 'Netherlands', coords: [4.30, 51.95], headcountBand: '500-2000', climateZone: 'temperate' },
  { id: 'A-HOL-HYD', name: 'Holland Hydrogen 1', segment: 'renewables', region: 'EMEA', country: 'Netherlands', coords: [4.07, 51.97], headcountBand: '100-500', climateZone: 'temperate' },
];
